### ISSUE TITLE
Meta: Export to PDF

### ISSUE THREAD

**Issue by jstsddg** [nclskfm/dhbw-studienarbeit-muehle#169]
Für die Abgabe müssen die relevanten Notebooks in einer PDF zusammengefasst werden.

- [x] Erstellen der PDF
- [x] Hochladen der PDF (DHBW)
- [x] Hochladen der PDF (GitHub)
- [x] Erstellen eines Git-Tags
- [x] Link zu der PDF in die [README](README.md) Datei
- [x] Link zu dem Git-Tag in die [README](README.md) Datei
- [x] Physikalische Abgabe

**Comment by jstsddg** [comment]
We did it! 🥳
@benfu99 @nclskfm

**Comment by nclskfm** [comment]
Wup wup 🎊

**Comment by benfu99** [comment]
🍾
